//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace imperative.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("imperative.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spaces(ignore) = /[ \t]+/
        ///newlines(optional) = /(\s*\n)+\s*/
        ///comma = &quot;,&quot;
        ///comma_or_newline = newlines | comma
        ///semicolon_or_newline = newlines | &quot;;&quot;
        ///line_comment(ignore) = &quot;//[^\r\n]*&quot;
        ///string_value = /&quot;([^&quot;]*)&quot;|\G&apos;([^&apos;]*)&apos;/
        ///bool_value = &quot;true&quot; | &quot;false&quot;
        ///float_value = /-?(?:[0-9]*\.)?[0-9]+/
        ///int_value = /-?[0-9]+/
        ///path_separator = &quot;.&quot;
        ///arrow = &quot;=&gt;&quot;
        ///insert = /\$\w*/
        ///complex_set_operator = &apos;+=&apos; | &apos;-=&apos; | &apos;*=&apos; | &apos;/=&apos; | &apos;@=&apos;
        ///operator_token = &apos;+&apos; | &apos;-&apos; | &apos;/&apos; | &apos;*&apos; | &apos;&lt;=&apos; | &apos;&gt;=&apos; | &apos;&lt;&apos; | &apos;&gt;&apos; | &apos;==&apos; | &apos;!=&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string imp_lexer {
            get {
                return ResourceManager.GetString("imp_lexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start = @(namespace_class, newlines, 1, 0)
        ///
        ///namespace_class = namespace_statement | class_definition | enum_definition | import_statement | external_var | function_definition
        ///
        ///snippets = @(snippet_function, semicolon_or_newline, 1, 0)
        ///
        ///id = id_token | insert
        ///
        ///meta_list = meta_list_start @(id, comma_or_newline, 1, 0) array_end
        ///
        ///external_var = external var id @(type_info, 0, 1)
        ///
        ///operator = operator_token | insert
        ///
        ///comma_or_newline = comma | newlines
        ///
        ///value_type = string | bool | int | float |  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string imp_grammar {
            get {
                return ResourceManager.GetString("imp_grammar", resourceCulture);
            }
        }
    }
}
